# Generated by Django 5.0.3 on 2024-04-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
